# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snipkit < Formula
  desc "Access snippets from your favorite snippet manager without leaving the terminal"
  homepage "https://github.com/lemoony/snipkit"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lemoony/snipkit/releases/download/v0.0.3/snipkit_0.0.3_darwin_arm64.tar.gz"
      sha256 "100c005c78fc88d13d08dbb05e60ae27a7e7d88ddb089e385c4d15b47cda358c"

      def install
        bin.install "snipkit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lemoony/snipkit/releases/download/v0.0.3/snipkit_0.0.3_darwin_amd64.tar.gz"
      sha256 "4217b3604fe2576dc5af04b4c4374ac962c8a9766a8daebe81049725f7ecfc09"

      def install
        bin.install "snipkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lemoony/snipkit/releases/download/v0.0.3/snipkit_0.0.3_linux_amd64.tar.gz"
      sha256 "9a790bdfd59dde912de107f72f53c0fcb9ec1f06450d7379008e6a77a9850635"

      def install
        bin.install "snipkit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lemoony/snipkit/releases/download/v0.0.3/snipkit_0.0.3_linux_armv6.tar.gz"
      sha256 "6545ee130f74221f8a2428615bb6521ab5de091a4f7c5f7004e67d9622117e4c"

      def install
        bin.install "snipkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lemoony/snipkit/releases/download/v0.0.3/snipkit_0.0.3_linux_arm64.tar.gz"
      sha256 "a441336b9acf08287ec0c62398088f36a1afbe0f8eed2b1e0bd4975fe55a279a"

      def install
        bin.install "snipkit"
      end
    end
  end

  test do
    system "#{bin}/snipkit", "--version"
  end
end
